### ISSUE TITLE
Installation via conda fails on Windows

### ISSUE THREAD

**Issue by asteppke** [HEXRD/hexrd#532] opened 2023-06-10 12:46 UTC
When trying to start hexrd/hexrdgui after following the installation path through conda the software cannot be started. 

On Windows 11 I followed the manual and tried:
````
conda create -n hexrdgui
conda activate hexrdgui
conda install -c hexrd -c conda-forge python=3.10 hexrdgui
````

This runs without issues and generates the 
[attached environment](https://github.com/HEXRD/hexrd/files/11712444/env.txt) which looks fine:
````
hexrd                     0.9.2                   py310_0    hexrd
hexrdgui                  0.9.5           py310h61cd40d_0    hexrd
[...]
python                    3.10.11         h4de0772_0_cpython    conda-forge
````

Then starting the software either via
`hexrdgui`, `hexrdgui --help` or `hexrd` does not work and it returns without error message to the command line:
````
(hexrdgui) C:\Users\Alexander>hexrdgui --help

(hexrdgui) C:\Users\Alexander>
````

Can you give me a hint how to diagnose this issue?

**Comment by psavery** [comment] 2023-06-10 15:55
Yes, I just ran into this same issue yesterday, in fact. The “lxml” library version 4.9.1 is causing windows to crash silently when it is imported.

We depend on “lxml” because for some file formats, we use fabio, which installs it.

Can you try upgrading lxml to 4.9.2? That fixed it for me, and we are going to put that in as a requirement soon.

Run: ‘conda install -c conda-forge lxml==4.9.2’

Then try starting up the GUI again. Let me know how it goes.

We are about to come out with a new release in the next few days, which is going to include many new features. Feel free to try the prerelease, as it includes these already.

**Comment by psavery** [comment] 2023-06-11 02:51
@asteppke Yeah, we fixed that issue recently too! It was caused by a recent change in numpy (and upgrading lxml might have required you to upgrade your numpy as well). Dependencies can be difficult!

Well, they should all be fixed in the new release in a few days. I'm glad the Windows ZIP is working fine - it used all of the latest dependency versions at the time it was built.

About the `hexrd` tests - yes, they require [this repository](https://github.com/hexrd/examples), and you specify the path to it via the environment variable `HEXRD_EXAMPLE_REPO_PATH` (see our CI example [here](https://github.com/HEXRD/hexrd/blob/8d970fdfd49c7d557f8ee82cd57df51669f50dd7/.github/workflows/test.yml#L75)).

**Comment by psavery** [comment] 2023-06-21 02:33
@asteppke sorry, I forgot to follow up with the release info! We did end up generating the packages for the release, and you can find them here! https://github.com/HEXRD/hexrdgui/releases/tag/0.9.6

Please let us know if you need anything else. Thank you!

**Closed by psavery** 2023-06-21 02:33 UTC

**Comment by asteppke** [comment] 2023-06-22 10:36
@psavery Works like a charm, thank you very much!
