### ISSUE TITLE
Add CI for fit grains

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrd#65] opened 2020-08-07 13:18 UTC

**Comment by cjh1** [comment] 2020-08-07 19:48
@joelvbernier If you can provide the command line invocation and data, I can turn it into a CI test.

**Comment by joelvbernier** [comment] 2020-08-10 22:14
wokring on this right now...

**Comment by joelvbernier** [comment] 2020-08-10 23:14
@johnkit looks like we might have clobbered the output to grains.out for the fit-grains CLI entry point?

**Comment by johnkit** [comment] 2020-08-11 00:15
@joelvbernier not sure I follow. Do you mean that that fit-grains command overwrites the `grains.out` file previously generated by find-orientations? Yes that is how it works, but I think that's how it worked before the recent file I/O changes, no?

**Comment by joelvbernier** [comment] 2020-08-12 16:44
I just ran it and it did not write grains.out at all.

**Comment by cjh1** [comment] 2020-08-12 16:48
@johnkit Can you take a look? @joelvbernier I assume you are on master?

**Comment by johnkit** [comment] 2020-08-12 17:29
@joelvbernier  here is my usual this test case:

```
> cd .../hexrd-examples/NIST_ruby/multiruby_dexelas/include
> hexrd find-orientations --hkls 0,1,2 mruby_config_composite.yml
> hexrd fit-grains -f mruby_config_composite.yml
```

The resulting output includes directory `results_mruby_composite_hexrd07_py38` with the grains.out file.

```
drwxr-xr-x  5 john  staff   160 Aug 12 13:17 ff1_0_0
drwxr-xr-x  5 john  staff   160 Aug 12 13:18 ff1_0_1
drwxr-xr-x  5 john  staff   160 Aug 12 13:18 ff1_1_0
drwxr-xr-x  5 john  staff   160 Aug 12 13:18 ff1_1_1
drwxr-xr-x  5 john  staff   160 Aug 12 13:18 ff2_0_0
drwxr-xr-x  5 john  staff   160 Aug 12 13:18 ff2_0_1
drwxr-xr-x  5 john  staff   160 Aug 12 13:18 ff2_1_0
drwxr-xr-x  5 john  staff   160 Aug 12 13:18 ff2_1_1
-rw-r--r--  1 john  staff   483 Aug 12 13:19 fit-grains.log
-rw-r--r--  1 john  staff  1964 Aug 12 13:19 grains.out
```

Are these the right steps? If so, can you duplicate this or give me a failing example?

**Comment by joelvbernier** [comment] 2020-08-12 19:58
@johnkit -- just did a fresh install and seems to be working.  sorry for the false alarm.  Back to the CI test...

**Comment by joelvbernier** [comment] 2020-08-13 18:56
Actually, edit on this.  It appears to *not* write a `grains.out` file if one doesn't exist in the working directory to begin with, which is very strange.  I realize that I need to fix the logic in `fitgrains.py`, because the fitting process  _doesn't_ strictly need a grains.out file to exist; it can create the initial guess from the `find-orientations` output (accepted_orientations*.dat).  Furthermore, if `fit_grains:estimate` is specified in the config file, then it should disregard the check on whether the `find-orientations` has been run, as that is irrelevant in that case.

**Comment by joelvbernier** [comment] 2020-08-13 19:03
Confirmed that even with a `grains.out` file there, it is not updating it.  The reflection tables (`spots_XXXXX.out`) are, but not `grains.out`.  Running off of hexrd master.

**Comment by johnkit** [comment] 2020-08-13 19:37
@joelvbernier  I don't seem to be able to reproduce this. Are you using a dataset that you can send me?  I start with a clean hexrd-examples repo and run fit-grains like this:

```
> cd .../hexrd-examples/NIST_ruby/multiruby_dexelas/include
> hexrd fit-grains mruby_config_composite.yml
```
A file is generated at 'results_mruby_composite_hexrd07_py38/grains.out` when find-orientations completes.

I just reran and, after the find-orientations part, I manually copied the grains.out file so that I can compare with the grains.out that gets (over)written at the end of fit-grains. I'll append both files for reference - I changed the extensions to .log because github won't let me upload a .out file.

[find.out.log](https://github.com/HEXRD/hexrd/files/5071056/find.out.log) is the version that is output after the find-orientations has finished.

[grains.out.log](https://github.com/HEXRD/hexrd/files/5071052/grains.out.log) is the what is output at the end of the fit-grains (after hexrd exits).

As for environment:
* hexrd:master (c0f67a2f472 10-Aug-2020)
* macOS 10.14.6 (Mojave)
* Python 3.8.3 (python.org python, **not** conda)

**Comment by joelvbernier** [comment] 2020-08-13 19:43
@johnkit I think I need to remove the generation of the `grains.out` from the find-orientations command, as it is confusing.  The unique output from that step is the `accepted_orientations` file.  Can you confirm that if you delete the grains.out after find-orientations runs that it writes a new one?

I also just realized that I am running on a folder that is in the cloud (iCloud service) and that seems to be causing some weirdness...

**Comment by johnkit** [comment] 2020-08-13 20:01
@joelvbernier I suppose iCloud could balk at overwriting the grains.out file, but you would think there would be some kind of warning/message.

I just ran this test from a clean hexrd-examples, deleting the grains.out file generated by find-orientations:

```
> cd .../hexrd-examples/NIST_ruby/multiruby_dexelas/include
> hexrd find-orientations --hkls 0,1,2 mruby_config_composite.yml
> rm results_mruby_composite_hexrd07_py38/grains.out
> hexrd fit-grains mruby_config_composite.yml -f
```
and fit-grains did write out the grains.out file (along with the other results).

**Comment by cjh1** [comment] 2020-08-13 20:22
Just as another data point, I just ran with @johnkit 's instructions and also see the grains.out.

**Comment by joelvbernier** [comment] 2020-08-13 23:59
Ok -- so I am still seeing this issue, now in a different way.  I am running an example analysis on CHESS ([the single GE case](https://github.com/HEXRD/examples/blob/master/NIST_ruby/single_GE/include/ruby_config.yml)), which is a 6-document YAML config.  The grains.out gets written for the first, and none of the others.  
```
results_ruby_hexrd07_py38_scan_0:
total 8
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:46 GE
-rw-r--r-- 1 bernier2 chess 374 Aug 13 19:46 fit-grains.log
-rw-r--r-- 1 bernier2 chess 982 Aug 13 19:49 grains.out

results_ruby_hexrd07_py38_scan_1:
total 4
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:46 GE
-rw-r--r-- 1 bernier2 chess 202 Aug 13 19:47 fit-grains.log

results_ruby_hexrd07_py38_scan_2:
total 4
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:47 GE
-rw-r--r-- 1 bernier2 chess 202 Aug 13 19:48 fit-grains.log

results_ruby_hexrd07_py38_scan_3:
total 4
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:48 GE
-rw-r--r-- 1 bernier2 chess 202 Aug 13 19:48 fit-grains.log

results_ruby_hexrd07_py38_scan_4:
total 4
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:48 GE
-rw-r--r-- 1 bernier2 chess 202 Aug 13 19:49 fit-grains.log

results_ruby_hexrd07_py38_scan_5:
total 4
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:49 GE
-rw-r--r-- 1 bernier2 chess 202 Aug 13 19:49 fit-grains.log
```
Now this is a serial case.  For the multiprocessed case, the process fails for the second document when trying to concatenate the results (the call to `pull_spots` is executed in parallel becuase all the spots files are there).  May be a related issue?

This is a linux OS (SL7).  I'll roll back commits to see where it broke, but it is 1) definitely broken, and 2) in need of fixing ASAP as we are trying to run some large-scale analyses before Monday.  Please run the example I linked above and confirm.

**Comment by joelvbernier** [comment] 2020-08-14 00:43
Also confirmed running the same problem of the commit bf2658443abe2f2d16f295207b44953ad2cb1ed5 prior to @johnkit's pr #62 that I get the proper output.  So something in pr #62 broke the "standard" ascii output in `hexrd fit-grains`.  I don't have time today to track it down, hopefully you can fix it tomorrow? 
```
(hexrd_0.7) [bernier2@lnx301 include]$ ls -ltr results_ruby_hexrd07_py38_scan_*
-rw-r--r-- 1 bernier2 chess 545008 Aug 13 19:46 results_ruby_hexrd07_py38_scan_0_ruby_eta-ome_maps.npz

results_ruby_hexrd07_py38_scan_0:
total 8
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:46 GE
-rw-r--r-- 1 bernier2 chess 982 Aug 13 20:26 grains.out
-rw-r--r-- 1 bernier2 chess 474 Aug 13 20:26 fit-grains.log

results_ruby_hexrd07_py38_scan_1:
total 8
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:46 GE
-rw-r--r-- 1 bernier2 chess 982 Aug 13 20:27 grains.out
-rw-r--r-- 1 bernier2 chess 202 Aug 13 20:27 fit-grains.log

results_ruby_hexrd07_py38_scan_2:
total 8
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:47 GE
-rw-r--r-- 1 bernier2 chess 982 Aug 13 20:27 grains.out
-rw-r--r-- 1 bernier2 chess 202 Aug 13 20:27 fit-grains.log

results_ruby_hexrd07_py38_scan_3:
total 8
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:48 GE
-rw-r--r-- 1 bernier2 chess 982 Aug 13 20:28 grains.out
-rw-r--r-- 1 bernier2 chess 202 Aug 13 20:28 fit-grains.log

results_ruby_hexrd07_py38_scan_4:
total 8
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:48 GE
-rw-r--r-- 1 bernier2 chess 982 Aug 13 20:29 grains.out
-rw-r--r-- 1 bernier2 chess 202 Aug 13 20:29 fit-grains.log

results_ruby_hexrd07_py38_scan_5:
total 8
drwxr-xr-x 2 bernier2 chess  36 Aug 13 19:49 GE
-rw-r--r-- 1 bernier2 chess 982 Aug 13 20:30 grains.out
-rw-r--r-- 1 bernier2 chess 202 Aug 13 20:30 fit-grains.log
```

**Comment by johnkit** [comment] 2020-08-14 12:20
@joelvbernier looking into this now.

**Comment by johnkit** [comment] 2020-08-14 13:29
@joelvbernier  thanks the detailed example. We found the bug in cli/fit_grains.py and just merged https://github.com/HEXRD/hexrd/pull/69 with the fix. In brief, the code was overwriting the scan 0 grains.out file for each scan.

**Comment by joelvbernier** [comment] 2020-08-25 23:52
@cjh1  and @johnkit 

Dropped a [package](https://drive.google.com/file/d/1UI1d2oAkKdUoY_86h86RI6_Dwcd3njAM/view?usp=sharing) up on the HEXRD shared drive that has a start for a CI test for `hexrd fit-grains`.  Not sure what you want it to return (currently just a boolean for pass/fail).  You can call the test inside the directory as follows:
```
(hexrd_0.7) Joels-MacBook-Air:CI_test joel$ python fit_grains_check.py ruby_config.yml reference_grains.out 
test passed
```

**Comment by joelvbernier** [comment] 2020-08-26 00:08
not so fast -- the actual CI code still needs to be added!

**Comment by cjh1** [comment] 2020-08-27 16:31
@joelvbernier Are the data files you upload available in our [examples repo](https://github.com/HEXRD/examples)? If not can we add them? I would like to keep all the data there is possible?

**Comment by joelvbernier** [comment] 2020-08-28 00:19
Yes, that data file is [here](https://github.com/HEXRD/examples/blob/master/NIST_ruby/single_GE/imageseries/RUBY_0000-fc_GE.npz).

**Comment by cjh1** [comment] 2020-09-01 14:37
Excellent, thanks, I have made a start on this.

**Comment by joelvbernier** [comment] 2021-07-23 20:06
this has been completed.

**Closed by joelvbernier** 2021-07-23 20:06 UTC
Labels: bug, high priority
