### ISSUE TITLE
configuration yaml not saving for dexelas in 0.8.6

### ISSUE THREAD

**Issue by kenygren** [HEXRD/hexrd#283] opened 2021-06-04 19:44 UTC
@joelvbernier When saving the configuration yaml, the dexela values are not populated - instead a generic ge yaml is generated. I do not know in which version this started but Kate suggests it may be related to issues that users are having with calibrations.

**Comment by joelvbernier** [comment] 2021-06-08 18:55
I have not been able to replicate this behavior -- can you provide the exact steps and versions of `hexrdgui` and `hexrd` that you are seeing this?

**Comment by joelvbernier** [comment] 2021-06-09 17:21
Any updates on this @kenygren?

**Comment by kenygren** [comment] 2021-06-09 17:48
Cannot reproduce it at the moment so we can close the issue.


Kelly Elizabeth Nygren, Ph.D.

Cornell High Energy Synchrotron Source

Cornell University

________________________________

**Comment by psavery** [comment] 2021-06-14 14:55
Closing. Please re-open if the issue is encountered again.

**Closed by psavery** 2021-06-14 14:55 UTC
